export const ADMIN_LOGIN_INITIAL = 'ADMIN_LOGIN_INITIAL'
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS'
export const ADMIN_LOGIN_FAILURE = 'ADMIN_LOGIN_FAILURE'

export const VENDOR_LOGIN_INITIAL = 'VENDOR_LOGIN_INITIAL'
export const VENDOR_LOGIN_SUCCESS = 'VENDOR_LOGIN_SUCCESS'
export const VENDOR_LOGIN_FAILURE = 'VENDOR_LOGIN_FAILURE'


export const ADMIN_LOGOUT_SUCCESS = 'ADMIN_LOGOUT_SUCCESS'
export const VENDOR_LOGOUT_SUCCESS = 'VENDOR_LOGOUT_SUCCESS'