export const PRODUCT_INITIAL = 'PRODUCT_INITIAL'
export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS'
export const PRODUCT_FAILURE = 'PRODUCT_FAILURE'

export const PRODUCT_ACCEPT_INITIAL = 'PRODUCT_ACCEPT_INITIAL'
export const PRODUCT_ACCEPT_SUCCESS = 'PRODUCT_ACCEPT_SUCCESS'
export const PRODUCT_ACCEPT_FAILURE = 'PRODUCT_ACCEPT_FAILURE'

export const ACCEPT_INITIAL = 'ACCEPT_INITIAL'
export const ACCEPT_SUCCESS = 'ACCEPT_SUCCESS'
export const ACCEPT_FAILURE = 'ACCEPT_FAILURE'

export const REJECT_INITIAL = 'REJECT_INITIAL'
export const REJECT_SUCCESS = 'REJECT_SUCCESS'
export const REJECT_FAILURE = 'REJECT_FAILURE'

export const UPLOAD_INITIAL = 'UPLOAD_INITIAL'
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS'
export const UPLOAD_FAILURE = 'UPLOAD_FAILURE'

export const VENDOR_PRODUCT_INITIAL = 'VENDOR_PRODUCT_INITIAL'
export const VENDOR_PRODUCT_SUCCESS = 'VENDOR_PRODUCT_SUCCESS'
export const VENDOR_PRODUCT_FAILURE = 'VENDOR_PRODUCT_FAILURE'
