export const ADMIN_ADDUSER_INITIAL = 'ADMIN_ADDUSER_INITIAL'
export const ADMIN_ADDUSER_SUCCESS = 'ADMIN_ADDUSER_SUCCESS'
export const ADMIN_ADDUSER_FAILURE = 'ADMIN_ADDUSER_FAILURE'

export const ADMIN_VIEWUSER_INITIAL = 'ADMIN_VIEWUSER_INITIAL'
export const ADMIN_VIEWUSER_SUCCESS = 'ADMIN_VIEWUSER_SUCCESS'
export const ADMIN_VIEWUSER_FAILURE = 'ADMIN_VIEWUSER_FAILURE'

